// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404054241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Bill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("backend.Models.BillItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CatalogItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("backend.Models.CatalogItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = "6b29fc40-ca47-1067-b31d-00dd010662da",
                            DefaultPrice = 50m,
                            Name = "Adult Ticket",
                            TaxRate = 10m,
                            Type = "Entrance Fee"
                        },
                        new
                        {
                            Id = "6b29fc40-ca47-1067-b31d-00dd010662db",
                            DefaultPrice = 25m,
                            Name = "Child Ticket",
                            TaxRate = 10m,
                            Type = "Entrance Fee"
                        },
                        new
                        {
                            Id = "6b29fc40-ca47-1067-b31d-00dd010662dc",
                            DefaultPrice = 35m,
                            Name = "Senior Ticket",
                            TaxRate = 10m,
                            Type = "Entrance Fee"
                        },
                        new
                        {
                            Id = "6b29fc40-ca47-1067-b31d-00dd010662dd",
                            DefaultPrice = 150m,
                            Name = "VIP Pass",
                            TaxRate = 10m,
                            Type = "Entrance Fee"
                        },
                        new
                        {
                            Id = "6b29fc40-ca47-1067-b31d-00dd010662de",
                            DefaultPrice = 30m,
                            Name = "T-Shirt",
                            TaxRate = 5m,
                            Type = "Selling Price"
                        },
                        new
                        {
                            Id = "6b29fc40-ca47-1067-b31d-00dd010662df",
                            DefaultPrice = 15m,
                            Name = "Mug",
                            TaxRate = 5m,
                            Type = "Selling Price"
                        },
                        new
                        {
                            Id = "6b29fc40-ca47-1067-b31d-00dd010662e0",
                            DefaultPrice = 0m,
                            Name = "General Donation",
                            TaxRate = 0m,
                            Type = "Donation"
                        });
                });

            modelBuilder.Entity("backend.Models.BillItem", b =>
                {
                    b.HasOne("backend.Models.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("backend.Models.Bill", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
