// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionsApi.Data;

#nullable disable

namespace TransactionsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328055633_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TransactionsApi.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Balance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1985.40m,
                            Balance = "$12,234.45",
                            Date = "2019-12-03",
                            Description = "HACKERBANK INC. DES:CCD+ ID: 33375894749",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 42.99m,
                            Balance = "$12,191.46",
                            Date = "2019-12-05",
                            Description = "AMAZON MKTPL DES:AMZN.COM ID: 994020234",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3250.00m,
                            Balance = "$15,441.46",
                            Date = "2019-12-07",
                            Description = "PAYROLL DES:DIRECT DEP ID: 887654321",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Amount = 15.99m,
                            Balance = "$15,425.47",
                            Date = "2019-12-10",
                            Description = "NETFLIX DES:SUBSCR ID: 442001233",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 89.34m,
                            Balance = "$15,336.13",
                            Date = "2019-12-12",
                            Description = "WHOLE FOODS MKT DES:PURCHASE ID: 00192344",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
